language: python
python:
    - "2.7"
    - "3.2"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy python-scipy python3-numpy python3-scipy
script: python -m krypy.tests.tests
